package Exception;

public class App {

    public static void main(String[] args) {
        System.err.println("#1.in");
        //put code here
        System.err.println("#1.out");
    }

    public static void f() {
        System.err.println(".   #2.in");
        //put code here
        System.err.println(".   #2.out");
    }

    public static void g() {
        System.err.println(".   .   #3.in");
        //put code here
        System.err.println(".   .   #3.out");
    }

    public static void h() {
        System.err.println(".   .   .   #4.in");
        //put code here
        System.err.println(".   .   .   #4.out");
    }
}


